### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by benhosmer** [radiantbluetechnologies/ossim-geotools#1]
How do I build this and use it? What versions of grails etc. is it intended for?

**Comment by kitplummer** [comment]
A README containing build, run and license requirements should be in ALL projects.

**Comment by gpotts** [comment]
Is the Apache 2.0 license the least restrictive?  I'll add that as the license example for this project if that is the case.  I do not like a GPL for that is too restrictive.  I would like to have a license that allows one to use in proprietary solutions as well

**Comment by gpotts** [comment]
Readme file added
