### ISSUE TITLE
Client: Toolbar: Define AOI for cuts

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#10]
Define regions of interest to cut and export

* Allow one to draw a bounding box for selecting the region to cut
* Allow one to adjust the cut box by redrawing
* Add a “Create Geopackage” button to execute the cut defined

!story G1.3
!component Client UI

**Comment by melbsurfer** [comment]
Added two new toolbars over the maps, and moved the 'Manage Layer' dropdown to the Tile Map toolbar.  Also added a place holder for an 'Auto-refresh map' toggle to the 'Tools' dropdown on the Tile Map toolbar.
