### ISSUE TITLE
Client: Modal for product definitions

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#11]
Add a wizard for defining the product definitions for download and export
* Add a page that gives a summary of what they selected
* Add a page to make any modifications to what is being exported
* The page should be auto filled based on the underlying tiles that exist in the tile store. 
* Add submit button to submit the product export SPEC for processing

This is the web interface part. Rabbit part filed separately.

!story G1.4
!component web interface

**Comment by melbsurfer** [comment]
Client: Add parameters to geopackage output modal

**Comment by melbsurfer** [comment]
Working on the file download portion that will be provided once the product has been constructed.

**Comment by melbsurfer** [comment]
File/product download is now working via hyperlink. Going to circle back, and tweak the UI process for creating the link.  Make it a little more user friendly...

**Comment by melbsurfer** [comment]
Product UI enhancement is now complete.  The new UI provides feedback during product states of 'READY', 'RUNNING', 'FINISHED', and 'FAILED'

**Comment by melbsurfer** [comment]
Fixed a bug with the event listener being duplicated on the download
button DOM element

**Comment by melbsurfer** [comment]
Adding validation to name input on form
