### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by melbsurfer** [radiantbluetechnologies/ossim-geotools#118]
Need to know what browsers we need to support.  As of now we are looking at IE9+, FF 10+, Chrome?

**Comment by melbsurfer** [comment]
IE8???

**Comment by melbsurfer** [comment]
Note: The Openlayers 3 .js library does not work out of the box with Internet Explorer 8

**Comment by mpgerlek** [comment]
Need to check with AGC on version of IE on deployed laptops.

(mpg to take on for Sprint 3)

**Comment by mpgerlek** [comment]
entered issue 102 in omar-agc-pm, to replace this one
