### ISSUE TITLE
Estimation for download metrics

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#12]
Estimated metrics of size and time to complete download should be reported to user in reference to the most common categories of tactical bandwidth. Suggested options for reducing size, such as scale elimination or shrinking AOI by x number of units should be easily presented to the user.  C.5.g.

(open question: what is customer’s expectation for accuracy?)

!story G1.7
!component services

**Comment by gpotts** [comment]
Initial implementation will be a rudimentary implementation for size estimates.

**Comment by gpotts** [comment]
I have checked this in.  We will work on debugging bug will close this out
