### ISSUE TITLE
Admin UI AOI Selection constraint

### ISSUE THREAD

**Issue by gpotts** [radiantbluetechnologies/ossim-geotools#120]

**Comment by melbsurfer** [comment]
Added two new toolbars over the maps, and moved the 'Manage Layer' dropdown to the Tile Map toolbar.  Also added a place holder for an 'Auto-refresh map' toggle to the 'Tools' dropdown on the Tile Map toolbar.

**Comment by melbsurfer** [comment]
Fixed bug in AOI cutting tools
Draw interaction was not being removed when turning ‘cutting off’.  The
drawInteraction object is now being setActive(false)
