### ISSUE TITLE
Wizard for product definitions - rabbit side

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#13]
Rabbit message for #11.

!story G1.5
!component Client UI

**Comment by gpotts** [comment]
This is partly supported.  We have added a omar.tilestore.product queue.  We have tested a cut from the tilestore as a job added to the product queue.  We have pulled the product job from the queue.  We currently don't pass all parameters to the workflow.  I'll leave this open once we support all parameters being passed.  Might need to open a couple bug issues to represent the items needing updating in the workflow steps.
