### ISSUE TITLE
Admin OMAR WFS Feed

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#16]
This is the "WFS interface / calls to Omar" part of #15 

!story G2.1
!component Admin UI

**Comment by melbsurfer** [comment]
OMAR Feed is working in the admin page.  Need to move on to filtering by date (ingest and acquisition).  Also need to add functionality for  clicking on thumbnail, and adding image to the OMAR preview map.

**Comment by melbsurfer** [comment]
Created previewLayer function that grabs current selected OMAR image and adds the WMS to the OMAR preview map.

**Comment by melbsurfer** [comment]
Refactored previewLayer function to zoom to current OMAR image via clicking on the 'image card thumbnail'.  Code also throws a bounding box of the preview image on the mapTile so that the user can visually see where the image would be on the tile layer.

**Comment by melbsurfer** [comment]
Initial functionality for pulling from OMAR WFS is working.  Closing ticket
