### ISSUE TITLE
OL to visualize reference and tile set

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#17]
Use Openlayers to visualize reference and Tile Set(s) we are inserting or pushing data to
* Add Openlayers layer selector to allow for turning layers on and off
* Add a layer to Openlayers that will hold the currently active Tile Set
* Add our OSM reference layer
* Add a drop down to select the currently active master tile set

!story G2.2
!component Admin UI

**Comment by melbsurfer** [comment]
This functionality is present in the admin.gsp page
