### ISSUE TITLE
Tile Cache having problems with IE

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#177]
Tested clients IE 8,9,10 and 11

All of the IE clients had problems. Did not work well in the Tile Administrator selection.  Not loading the page correctly. Reporting errors about not fetching images, plus issues with rename and delete. Then IE8 never loaded in the Tile Administrator page.

**Comment by melbsurfer** [comment]
I can confirm that IE8 will not work properly with the Tilestore applications.  This stems from OpenLayers 3.  The javascript API does not support IE8.

As for IE, I am unable to view these issues. I have tested on Browser Stack, and on a local VM with IE9.  Closing issue.
