### ISSUE TITLE
Bounding box under problem under Chrome

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#178]
esting Tile Cache using Browser Stack.

Chrome 23 did not load Tile Chache.

Clients 14 to 18 we had some problem when drawing a bounding box, the viewer would turn a light blue but you could still use the Tile Viewer

**Comment by mpgerlek** [comment]
Moved Chrome-23 issue to new bug

**Comment by melbsurfer** [comment]
Can not replicate this problem in Chrome 14-18.  I am able to conduct an ingest, and create a product using a bounding box.  Closing ticket.
