### ISSUE TITLE
Tile cache not working under FireFox

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#179]
Testing Fire Fox on Tile Cache found that client version 3 to client version 10 is not working. Will not load the Tile Cache.

**Comment by melbsurfer** [comment]
I can confirm that the application will not load using these browsers.  However, the requirements are for Firefox 38+ so, I am closing this out.  It should be noted that the application is running fine on Firefox 11 and above.
