### ISSUE TITLE
Problems with Safari on Tile Cache

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#180]
Safari 5.1, 5.0 all got errors loading Tiles Administrator reporting that there was errors fetching images. Safari 4.0 did not load the Tiles Administrator.

**Comment by melbsurfer** [comment]
I can confirm the application will not load in Safari 4

**Comment by melbsurfer** [comment]
It should be noted that the application is working in Safari 5+; however, there were no requirements to support Safari.  Closing issue.
