### ISSUE TITLE
Client/Admin: Geo-Cord search set to DD and enter a DMS coordinates

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#184]
In the client and had the Geo-Cord search set to DD and enter a DMS coordinates. It move me to the wrong location but if you have the Geo-Cord set to DMS at the time of the search it will work correctly. Here is the DMS coordinates that I enter which is one of the Melbourne image.

285959.75N 0805959.75W

**Comment by melbsurfer** [comment]
Did a major refactor on the zoomTo module.  Needed to change some of the regular expressions that were being used for the DD, DMS, and MGRS inputs.

Changed the way the RegExp object was being used from RegExp.$N to pulling the actual parsed items from the array returned in the regular expressions per: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n  

Pulled in the mgrs.js library (https://github.com/proj4js/mgrs) to parse the coordinates coming in from the input.  Also moved the dmsToDd function from coordinate.js library to zoomTo.js.  This removes the dependency on that library for the DMS to DD functionality.  

**Hopefully** this module can now easily be reused in our other OL3 projects.
