### ISSUE TITLE
height and width are not changing when I change the bounding box size.

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#194]
Found that on tile viewer that the height and width are not changing when I change the bounding box size.   I tried a small rect and it stayed the same and said it was 32kx32k  which was way big for the little box I was drawing.

**Comment by gpotts** [comment]
The getActualBounds was not taking into consideration a crop AOI.  The bounds returned is now tile aligned number of pixels wide and high of the highest level of tiles
