### ISSUE TITLE
UI layer to CRUD interface

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#20]
UI - Implement CRUD based interfaces to create, Update, rename and Delete layers.  Update will include rename support
* Add a button to create a layer.  Add a UI for entering layer definitions when creating
* Add a button to update a layer definition.  Use the similar create UI and allow certain fields to be updated.
* Add a button to rename a layer.  Add a UI that allow one to rename a master tile set
* Button for rename

!story G2.6
!component Admin UI

**Comment by melbsurfer** [comment]
Refactoring the buttons to gain a little more screen real estate.

**Comment by melbsurfer** [comment]
CRUD operations have been moved to a dropdown list.
