### ISSUE TITLE
Tile Cache loading under Chrome 23

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#203]
Chrome 23 did not load Tile Cache.

Forked off from #178

**Comment by melbsurfer** [comment]
Will use Browser Stack to look into this.

**Comment by melbsurfer** [comment]
Tested ingest using Admin, and everything works fine.

**Comment by melbsurfer** [comment]
Successfully created geopackage on Chrome 23.  Can not reproduce bug, so I am closing this one out.
