### ISSUE TITLE
Blue dot on admin tile store

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#204]
There is the blue dot which is the open layer3 url and will move a user away from the tile store. The user will then need to click the back button to recover. The problem is with a new user if the user was to unknowing hit the dot they would think that they have lost all of their work.

**Comment by mpgerlek** [comment]
Is this a "bug" or an "enhancement", and is it "required" or "nice to have"?

**Comment by mpgerlek** [comment]
(moved from https://github.com/radiantbluetechnologies/omar-agc-pm/issues/116)

**Comment by melbsurfer** [comment]
This should be considered an enhancement.  Adding the label.

**Comment by melbsurfer** [comment]
This was an easy fix as OL3 has a map parameter option for the logo.  I set it to false in all of the maps.  This fix has been committed, and pushed to the dev branch.  It will not show up until Garrett has published the latest .war from the dev branch. Closing ticket.
