### ISSUE TITLE
(doc) Export Level Changes to 9/16

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#205]
BrowserStack - FireFox38 – Account logon is doconnorL ( layer manager) - Export Tile - This has been happening in other browser’s where I change the level of an image then the level changes on ingest to 9 and 16 when ingest is selected but you can only see level 10 to 17.

**Comment by mpgerlek** [comment]
Behaviour OK as-is -- need to document

**Comment by doconnor24** [comment]
The level has been documented in the User Guide
