### ISSUE TITLE
Layer not removed from Delete after rename

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#206]
BrowserStack - FireFox38 – Account logon is doconnorL ( layer manager) - Rename test4 to test5 – deleted test5 – When to delete another layer and test4 is still in the list of layers but test 4 is not listed in any others like rename or active. When to delete it and got an error that there is no test4.

**Comment by melbsurfer** [comment]
Refactored the create, rename and delete functionality to update the various select lists that display the layer names.  All selects should now have the correct listing after an operation is performed.
