### ISSUE TITLE
Update Test VM to the latest Accumulo version

### ISSUE THREAD

**Issue by gpotts** [radiantbluetechnologies/ossim-geotools#208]
This requires Accumulo 7.X to be downloaded and installed on a single instance VM.  We will test connectivity and distribute to our other developers to use in their testing environment

**Comment by mpgerlek** [comment]
0d (covered in #211)

**Comment by gpotts** [comment]
I now have a test VM that has Accumulo 7 and cloudier 5.4.4.  I'll now try t build to these versions and see if the tilestore can connect to that accumulo
