### ISSUE TITLE
Update our unclassified test site to latest cloudera

### ISSUE THREAD

**Issue by gpotts** [radiantbluetechnologies/ossim-geotools#211]
Update our test site on mar.ossim to the latest and greatest cloudera.

**Comment by mpgerlek** [comment]
0d (covered in #212)

**Comment by gpotts** [comment]
I have updated to the latest cloudera.  Seems that in the past couple days they have updated to CDH5.4.5.  So CDH5.4.5 is installed on the test site and is fully updated
