### ISSUE TITLE
Refactor workflow for latest hadoop setup

### ISSUE THREAD

**Issue by gpotts** [radiantbluetechnologies/ossim-geotools#212]
I know that the latest data-integration has removed a few API's and will need updating to fix  during this upgrade.  This will also mean that the grade build environment will need updating for the plugin steps used in the data-integration/kettle environment

**Comment by mpgerlek** [comment]
5-10d

**Comment by gpotts** [comment]
I might go ahead and close this.  I have tested a local connection to an accumulo 1.7.0 with coudera 5.4.4 for the tilestore implementation
