### ISSUE TITLE
Need to support Local tiling

### ISSUE THREAD

**Issue by doconnor24** [radiantbluetechnologies/ossim-geotools#218]

**Comment by gpotts** [comment]
We will have to edit the geopackage core writer to support instantiation with parameters that identify this as a local tiling but global GSD specification.  After using a sqliteman explorer on the mac this appears to be what the sample dataset we have does.

**Comment by gpotts** [comment]
We are almost finished with the local tiling.  We are currently adding a keyword(s) to be passed to the core writer from the workflow.  We have tested by "hardcoding" some flags to turn the internal off and on for the workflow test and the local bounds with global tiling seems to be working well.  We will clean this up today and finalize

**Comment by gpotts** [comment]
We have finished the local tiling and once we get the RPM builds for the core I'll update the test site for testing.  For now I am going to close this out
