### ISSUE TITLE
Client: 4326 Geopackage export issue

### ISSUE THREAD

**Issue by melbsurfer** [radiantbluetechnologies/ossim-geotools#225]
Issue on export page when attempting to output a geopackage in 4326

**Comment by melbsurfer** [comment]
Looked into this, and it appears that the demo site can not export geopackages in 4326.  However it is working on my local instance (laptop).  Will need to follow up with Garrett.

**Comment by gpotts** [comment]
When I update the site next I will verify the workflows and verify the reproduction.  I am assuming that you are exporting a tilestore layer that is 3857 into a 4326 geopackage

**Comment by melbsurfer** [comment]
Yes, the export is from a 3857 layer --> 4326 geopackage

**Comment by gpotts** [comment]
I have updated everything and the retroject seems to run fine
