### ISSUE TITLE
Pull workflows from bunny rabbit

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#39]
Add workflows to pull from a Rabbit queue and extract SPEC settings

!story G9.3
!component workflow job

**Comment by gpotts** [comment]
This is going to be a little bigger than medium.  Probably take a full week for this.  Changed to be Size-L

**Comment by mpgerlek** [comment]
Could it be broken into smaller tasks?

-mpg



On Apr 27, 2015, at 8:51 AM, gpotts <notifications@github.com<mailto:notifications@github.com>> wrote:


This is going to be a little bigger than medium. Probably take a full week for this. Changed to be Size-L

**Comment by gpotts** [comment]
Probably.  Just get's more complicated to support different clustering, ... etc.  Let me look at it and as I start the implementation I might break it out into a couple mediums.  Not sure of the steps I'll have to implement. Basically takes about 2 to 3 days per new step in data-integration/kettle environment for me to implement.  Then helping hook it up to the job being submitted from the UI.

**Comment by gpotts** [comment]
I have broken this out into a message SPI task.  This way this will be 2 medium sized implementation.

**Comment by gpotts** [comment]
We have added a RabbitMQ pull for the workflow in data-integration environment and can pull a message and execute the message for ingesting.  We will need another issue for doing messages for the Geopackage and WMTS tree outputs.
