### ISSUE TITLE
ossim-tools gradle build fails on github sources

### ISSUE THREAD

**Issue by benhosmer** [radiantbluetechnologies/ossim-geotools#4]
https://github.com/radiantbluetechnologies/ossim-geotools/blob/develop/ossim-tools/build.gradle

https://github.com/radiantbluetechnologies/ossim-geotools/blob/develop/ossim-tools/build.gradle#L120

`url 'https://github.com/ElectronicChartCentre/ecc-mvn-repo/tree/master/releases'`

perhaps should be

`url 'https://github.com/ElectronicChartCentre/ecc-mvn-repo/raw/master/'`

**Comment by gpotts** [comment]
Hello Been.  Have you tried it?  Also,  if you have it downloaded via a previous compilation and you want to try to see if it will download using the grade process then you can just remove ~/.m2 and directory ~/.gradle and then test the gradle build again.  This way the local repo is tested.  The link https://github.com/ElectronicChartCentre/ecc-mvn-repo/raw/master/ is a 404 and if I tack on https://github.com/ElectronicChartCentre/ecc-mvn-repo/raw/master/releases it redirects to the link https://github.com/ElectronicChartCentre/ecc-mvn-repo/tree/master/releases

**Comment by benhosmer** [comment]
I didn't have a chance to try it, but I wanted to capture the idea quickly
so I could go back and try it later. Github doesn't work like a normal
directory listing or file system would and I suspect that has something to
do with it. The maintainer hasn't tagged any releases, which makes it a tad
more difficult to get assets.

If I can eliminate maven, that simplifies things and I'd like it to work
without building twice. Locally it isn't a big deal, but this adds time and
steps to automated builds.

On Sat, Apr 11, 2015 at 9:11 AM, gpotts <notifications@github.com> wrote:

> Hello Been. Have you tried it? Also, if you have it downloaded via a
> previous compilation and you want to try to see if it will download using
> the grade process then you can just remove ~/.m2 and directory ~/.gradle
> and then test the gradle build again. This way the local repo is tested.
> The link https://github.com/ElectronicChartCentre/ecc-mvn-repo/raw/master/
> is a 404 and if I tack on
> https://github.com/ElectronicChartCentre/ecc-mvn-repo/raw/master/releases
> it redirects to the link
> https://github.com/ElectronicChartCentre/ecc-mvn-repo/tree/master/releases
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiantbluetechnologies/ossim-geotools/issues/4#issuecomment-91843679>
> .
>



-- 
Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by benhosmer** [comment]
The pattern for github repos is like this:
`https://github.com/USERNAME/REPONAME/raw/master`

**Comment by benhosmer** [comment]
Fixed with f819d16
