### ISSUE TITLE
Add step to extract tiles

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#41]
Workflow Updates for extracting and exporting tiles from the Tile Store...

Add Tile Store step to extract tiles
* Create Step meta defitions plugin
* Create the step UI plugin definitions
* Create the Step executor definitions

(JNI interface)

!story G10.1
!component workflow

**Comment by gpotts** [comment]
Been thinking about this.  I was going to re-use the tile generator but if there are weird cuts that do not follow a rectangle or square but are concave then it is faster to tie this step to a tile generator that intersects the WKT Area Of Interest poly with the database.  This way only the tiles that are present will be iterated over.

We will add constraints:

1.  WKT Area of interest
2. clamp min level max level

**Comment by gpotts** [comment]
A Tile extractor is implemented.  It is rudimentary for it just iterates over a tilestore given the bounds.
