### ISSUE TITLE
Ability to cut geopkg from KML/SHP

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#48]
ability to cut geopkg for AOI with KML/SHP

!story G11.5
!component web interface

**Comment by gpotts** [comment]
In order for us to address this we still need the format of these.  For if you cut with KML it will not be a full KML document but probably a subset.  Need to know what the message/KML structure will look like for a KML cut definition

**Comment by gpotts** [comment]
Looks like for KML it should be a <placemark> tag given to us

**Comment by gpotts** [comment]
Service has been added.  We are now ready to test and add to the client UI to upload a cut definition

**Comment by gpotts** [comment]
Cut is being passed to the product export
