### ISSUE TITLE
OGC interfaces for Tile Set visualization

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#7]
Use Openlayers OGC interfaces for master Tile Set visualization

Add Openlayers layer selector to allow for turning layers on and off
Add a layer to Openlayers that will hold the currently active Tile Set
Add our OSM reference layer

!component WMS/WFS
!story G1.1

**Comment by mpgerlek** [comment]
Use Openlayers OGC interfaces for master Tile Set visualization

* Add Openlayers layer selector to allow for turning layers on and off
* Add a layer to Openlayers that will hold the currently active Tile Set
* Add our OSM reference layer

! component WMS/WFS
! story 1.1

**Comment by sbortman** [comment]
After talking w/Aaron.   I *think* this one is done.   Closing for now.
