### ISSUE TITLE
Build RPMs

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#71]
Build RPMs

!story G16.1
!component CI/CD

**Comment by benhosmer** [comment]
After starting a script to poll the ossim svn repo, I realized jenkins has this built in already: https://wiki.jenkins-ci.org/display/JENKINS/Subversion+Plugin

All we need to do is configure the current jenkins to poll the svn repo for changes.

**Comment by mpgerlek** [comment]
Assigning to @dburken as per @benhosmer. Will be slotted for Sprint 3.

**Comment by mpgerlek** [comment]
1- build on every commit via local jenkins
2- push the rpm to S3 bucket
