### ISSUE TITLE
Do ossim-batch-test

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#73]
Do ossim-batch-test

!story G17.1
!component test

**Comment by doconnor24** [comment]
I will run the ossim-batch-tests when we have a baseline built.

**Comment by doconnor24** [comment]
Will run the batch test when I get a baseline. Today we don't have any of the software in one compiled baseline. I have been running tests off of Aaron workstation.

**Comment by doconnor24** [comment]
This will happen when the baseline is tagged and move to server to run Ossim Batch Scritps.

**Comment by doconnor24** [comment]
Test Scripts have been run and reviewed. Had 6 questions the the tests

**Comment by doconnor24** [comment]
I have one question left on band selection running the scripts so I am going to close this issue and work with Garrett on the questions
