### ISSUE TITLE
Spock integration

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#74]
Spock integration

!story G17.7
!component test

**Comment by benhosmer** [comment]
I'm looking at webtest canoo right now for this. It offers Dennis an easier way to create tests. I'm building a vagrant fedora box that he can use.

**Comment by benhosmer** [comment]
As soon as the PR: https://github.com/radiantbluetechnologies/ossim-geotools/pull/94 is in, this can be closed out.

**Comment by mpgerlek** [comment]
Done, per @benhosmer.
