### ISSUE TITLE
Regression test doc / scenario - sell off of requirements

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#75]
Regression test doc / scenario - sell off of requirements

!story G17.2
!component test

**Comment by doconnor24** [comment]
Started to map requirements to the Regression scenario

**Comment by doconnor24** [comment]
This has happen. Spoke with Michael on his last visit and Michael said that we have met all of the requirements. I have the test map to these requirements.
