### ISSUE TITLE
Tile server user guide

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#79]
Tile server user guide

!story G18.3
!component docs

**Comment by doconnor24** [comment]
Work a little on this but with talking with Aaron I am to far a head of writing the doc. Still a lot of changing happening.

**Comment by doconnor24** [comment]
Working on the Doc. Was able to see the new UI's and ran some tests. This will help me on writing the steps and how to lay out the format. Thinking we should only have one doc with will have all of the roles in it.

**Comment by doconnor24** [comment]
Completed User Guide and waiting review.

**Comment by mpgerlek** [comment]
mpg to review

**Comment by mpgerlek** [comment]
now a dup of #164 in omar-agc-pm repo
