### ISSUE TITLE
Geocell user guide

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#82]
Geocell user guide

!story G18.4
!component docs

**Comment by dhicks10** [comment]
OSSIMGeoCell__User_Manual__1.8.18.doc resides on Google Drive and is shared with several individuals.  Dennis should have a copy.

**Comment by doconnor24** [comment]
I have the OSSIMGeoCell user Guide

**Comment by doconnor24** [comment]
We have not changed anything in OSSIMGeoCell user Guide. Only work on this doc was clean up by mpg.
