### ISSUE TITLE
User training docs and slides and videos

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/ossim-geotools#84]
User training docs

!story G18.7
!component docs

**Comment by doconnor24** [comment]
Michael
I think that the User Guide will be good enough with out doing a training doc. 
Can do videos if needed.

**Comment by mpgerlek** [comment]
We will need to give a ~45 min demo to the AGC folks, so we should have something. 

Suggestion: a video for each of the canonical workflows, plus a one-page word doc handout summarizing (1) what those canonical workflows are and (2) what other full-on docs are available?

Then again, perhaps we should talk about who is going to do that "training" session and let that person decide what's needed.

**Comment by mpgerlek** [comment]
OK, we will do vids -- Dennis is on it.

**Comment by mpgerlek** [comment]
We need:

(1) for each of the N workflows, a 2-3 min video [can be stored on YouTube, I suppose…]

(2) for each of the N workflows, a 1-3 PPT slides

(3) one "meta" document that contains ~1 paragraph describing each workflow, with pointers to the corresponding section(s) in the user manuals and to the video

**Comment by mpgerlek** [comment]
(moved to https://github.com/radiantbluetechnologies/omar-agc-pm/issues/178)
