### ISSUE TITLE
Instructions for getting and environment set up

### ISSUE THREAD

**Issue by benhosmer** [radiantbluetechnologies/ossim-geotools#88]
Refer to https://github.com/radiantbluetechnologies/ossim-geotools/blob/develop/README.md

This is incomplete and `gradle build` fails because it can't find a source for JOMS.

!story G16

**Comment by benhosmer** [comment]
I know there are some pieces missing as well. The accumulo isn't there at all for example.

**Comment by gpotts** [comment]
If you are building a baseline you will have to do a build of oms/joms:  using the command "ant mvn-install"

**Comment by benhosmer** [comment]
Gradle can't do that too I assume? In what directory do I run `ant
mvn-install`?


On Tue, Apr 14, 2015 at 1:35 PM, gpotts <notifications@github.com> wrote:

> If you are building a baseline you will have to do a build of oms/joms:
> using the command "ant mvn-install"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiantbluetechnologies/ossim-geotools/issues/88#issuecomment-92991353>
> .
>



-- 
Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by benhosmer** [comment]
Missing:

1. Configuration settings for a local or remote accumulo
2. Grails commands?
3. Someone other than me proofreading the document for accuracies.

**Comment by gpotts** [comment]
Added more docs to the README file under the ossim-geotools directory

**Comment by mpgerlek** [comment]
Folded these issues into #80 - closing this as dup
